name: active_matrimonial_flutter_app
description: A complete Flutter matrimonial application with Firebase, authentication, notifications, and admin integration.
publish_to: 'none' 
version: 2.6.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  expandable: ^5.0.1
  email_validator: ^3.0.0
  flutter_facebook_auth: ^7.1.2
  firebase_core: ^3.15.1
  flutter_redux: ^0.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^6.0.0
  flutter_html: ^3.0.0
  full_screen_image: ^2.0.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.6
  flutter_summernote: ^1.1.1
  google_sign_in: ^6.3.0
  http: ^1.6.0
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  image_picker: ^1.2.1
  multiselect: ^0.1.1
  markdown: ^7.3.0
  one_context: ^4.0.0
  pinput: ^5.0.2
  rename: ^3.1.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  toast: ^0.3.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  zoom_widget: ^2.0.1
  phonepe_payment_sdk: ^3.0.2
  connectivity_plus: ^7.0.0
  firebase_auth: ^5.7.0
  store_box: ^2.0.0
  info_getter: ^1.0.0
  path: ^1.9.1

dependency_overrides:
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/icon/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

